# This is a basic workflow to help you get started with Actions

name: Create and publish a Product on Amplify Marketplace

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-product:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Prepare Axway CLI on this container
      - name: Install Axway CLI
        run: |
          npm i -g axway
          axway pm install @axway/axway-central-cli
      
      # Runs a set of commands using the runners shell
      - name: Create Asset, Product, and publish Product to Marketplace
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          ./create-n-publish-product.sh
        shell: bash
